

REGISTER-3DMATCH:
  DATASET-NAME: '3DMATCH'
  DATASET-PATH: /data/3DMatch/
  OVERLAP-CSV-PATH: 'data/overlaps/3dmatch_overlap_predator.csv'
  METHOD-NAME: 'TESTING_SCRIPTS' 
  SET-SEED: True
  BATCH-SIZE: 8
  GPU-INDEX: 0
  VOXEL-SIZE: 0.06
  CONTINUE-RUN:  null # 'name-of-results-folder' like 2207250901
  ROTATION-OPTION: 'R_LIMITED_15_15_15'
  PADDING: 'same'
  PV: 5
  NV: -1
  PPV: -1
  NUM-WORKERS: 8

REGISTER-KITTI:
  DATASET-NAME: 'KITTI'
  DATASET-PATH: /data/KITTI/
  METHOD-NAME: 'TESTING_SCRIPTS' 
  SET-SEED: True
  BATCH-SIZE: 2
  GPU-INDEX: 0
  VOXEL-SIZE: 0.60
  CONTINUE-RUN:  null
  ROTATION-OPTION: 'R_LIMITED_15_15_15'
  PADDING: 'same'
  PV: 5
  NV: -1
  PPV: -1
  NUM-WORKERS: 8

REGISTER-ETH:
  DATASET-NAME: 'ETH'
  DATASET-PATH: /data/ETH/
  OVERLAP-CSV-PATH: 'data/overlaps/eth_overlap_perfect_match.csv'
  METHOD-NAME: 'TESTING_SCRIPTS' 
  SET-SEED: True
  BATCH-SIZE: 2
  GPU-INDEX: 0
  VOXEL-SIZE: 0.30
  CONTINUE-RUN:  null
  ROTATION-OPTION: 'R_LIMITED_15_15_15'
  PADDING: 'same'
  PV: 5
  NV: -1
  PPV: -1
  NUM-WORKERS: 8

REGISTER-FP:
  DATASET-NAME: 'FP'
  SCANS-PATH: '/data/FAUST/training/scans'
  BENCHMARK-PATH: '/data/FAUST/training' #'/data/FAUST-partial/ICO-12'
  METHOD-NAME: 'FAUST_partial'
  VOXEL-SIZE: 0.03 #3mm is resolution of FAUST
  BATCH-SIZE: 32
  GPU-INDEX: 0
  CONTINUE-RUN: null
  SET-SEED: True
  ROTATION-OPTION: 'R_15_15_15'
  PADDING: 'same'
  PV: 5
  NV: -1
  PPV: -1
  NUM-WORKERS: 8

DATASET-VARS:
  3DMATCH: 
    N: 1523
    THR-ROT: 15
    THR-TRANS: 0.3
  ETH:
    N: 713
    THR-ROT: 5
    THR-TRANS: 0.3
  KITTI:
    N: 555
    THR-ROT: 5
    THR-TRANS: 2
  FP:
    N: 1724 
    THR-ROT: 10
    THR-TRANS: 0.03 # 3cm
